# Configurações do Email
email:
  usuario: "chmulato@gmail.com"
  senha_app: "senha_gmail_app"  # Use uma senha de app do Gmail
  servidor_smtp: "smtp.gmail.com"
  porta: 587

# Configurações de Envio
envio:
  delay_entre_emails: 30  # segundos entre cada envio
  max_envios_por_dia: 10
  horario_funcionamento:
    inicio: "09:00"
    fim: "17:00"

# Configurações de Follow-up
followup:
  dias_para_seguimento: 7
  max_followups: 2

# Configurações de Arquivos
arquivos:
  curriculo: "currículo.pdf"
  empresas: "empresas.xlsx"
  log_respostas: "log/log_respostas.xlsx"
  template_email: "templates/mensagem_email.txt"
